### PR TITLE
Fix/announce

### LINKED ISSUE #71: create read-only drives with corestore session
don't close sdk.corestore on closing drive

### PR DESCRIPTION
**Pull request by Nazeh**
closes #71

### CODE REVIEW

File: packages/sdk/index.js [hunk 1]
```diff
@@ -135,7 +135,7 @@ export class SDK extends EventEmitter {
 
     // Announce the drive as a client
     const discovery = this.join(crypto.discoveryKey(key), { server: false, client: true })
-    drive.on('close', () => discovery?.destroy())
+    discovery && drive.once('close', () => discovery?.destroy())
```
Comment (mikeobank) [inline packages/sdk/index.js:138]: The optionality question mark on `discovery?` seems unnecessary

Comment (Nazeh) [reply packages/sdk/index.js:138]: Good catch thanks.
